/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package foodorder;

/**
 *
 * @author TALHA
 */
public class Order extends javax.swing.JFrame {

    /** Creates new form Order */
    public Order() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbobiryani = new javax.swing.JCheckBox();
        cboroll = new javax.swing.JCheckBox();
        cbodrink = new javax.swing.JCheckBox();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbobiryani.setText("Biryani @ Rs.120");

        cboroll.setText("Roll @ Rs.80");
        cboroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cborollActionPerformed(evt);
            }
        });

        cbodrink.setText("Drink @ Rs.50");
        cbodrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodrinkActionPerformed(evt);
            }
        });

        btnOrder.setText("ORDER");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(89, 89, 89)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(cbobiryani)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, cboroll)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, cbodrink)))
                    .add(layout.createSequentialGroup()
                        .add(139, 139, 139)
                        .add(btnOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(83, 83, 83)
                .add(cbobiryani)
                .add(26, 26, 26)
                .add(cboroll)
                .add(27, 27, 27)
                .add(cbodrink)
                .add(18, 18, 18)
                .add(btnOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cborollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cborollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cborollActionPerformed

    private void cbodrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodrinkActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        int biryani = 0; int roll =0 ; int drink = 0; 
        if (cbobiryani.isSelected())
        {
           biryani = 120; 
        }
        if (cboroll.isSelected())
        {
            roll = 80;
        }
        if (cbodrink.isSelected())
        {
            drink = 50;
        }
        new Tender(biryani, roll, drink).setVisible(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JCheckBox cbobiryani;
    private javax.swing.JCheckBox cbodrink;
    private javax.swing.JCheckBox cboroll;
    // End of variables declaration//GEN-END:variables

}
